[package]
name = "emcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asking = "0.0.2"
async-std = "1.12.0"
tokio = { version = "1.20.1", features = ["full"] }
