[package]
name = "emcs"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = "0.3.0"
async-std = "1.12.0"
reqwest = "0.11.11"
tokio = { version = "1.20.1", features = ["full"] }
c314-utils = "0.1.2"
